require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - gemfiles/vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Exclude:
    - 'spec/**/*'
